### ISSUE TITLE
ID collision

### ISSUE THREAD

**Issue by ukhachev** [AntonyMoes/A.C.I.D.#1]
ID collision in  EntityManager::add_entity() (entity_manager.cpp:9)

**Comment by AntonyMoes** [comment]
I suggest handling ID collisions in NetworkSystem, cause framework should manage it's internal IDs itself. Or maybe we could implement some out-of-box network support, such as gameloop's Server/Client specialization or smth

**Comment by AntonyMoes** [comment]
Resolved by not creating static position entities
